# Generated by Django 5.0.6 on 2024-05-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleApi', '0002_blogs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
